version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - sudo apt update -y
            - echo "installing source wordpress dependancies"
            - sudo apt install php-fpm php-mysql php-curl php-gd php-intl php-soap php-xml php-xmlrpc php-zip php-mbstring php-soap -y
    build:
        commands:
            - echo "we are starting the build block"
            - sed -i 's/database_name_here/'$DB_Name'/' wp-config.php
            - sed -i 's/username_here/'$DB_User'/' wp-config.php
            - sed -i 's/password_here/'$DB_Password'/' wp-config.php
            - sed -i 's/localhost/'$DB_Host'/' wp-config.php
            - echo build started on 'date'
            - echo "compiling the wordpress code"
            
    post_build:
        commands:
            - echo build Completed on 'date'
            
    artifacts:
            files:
              - '**/*'
